name: Node.js CI with Artifact Upload

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js v21.6.2
      uses: actions/setup-node@v3
      with:
        node-version: '21.6.2'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
    - name: Build Docker image
      run: docker build -t demo-mock-auth .
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: .  # You can specify the path to the build artifacts here
